### ISSUE TITLE
Additional info on cmb.dat

### ISSUE THREAD

**Issue by KarlClinckspoor** [hankmorgan/UWReverseEngineering#2]
I've messed around with `cmb.dat` some time ago, and I found a few things about it that could warrant being added to your description of this file. I detailed some of my findings [here](https://github.com/JohnGlassmyer/UltimaHacks/issues/23)

In short:

* There's a max of 10 item combinations. You can add more to `cmb.dat`, but the game won't recognize them.
* If two items aren't flagged for destroying, they combination won't go through, but no errors will be raised.
* If the created item can't be normally picked up, you won't be able to place it in your inventory
* Items with durability seem to be created with serviceable durability (I made a mistake in the text saying they are created with excellent durability, it's specific to the black sword)
* It's slightly different in UW1 and UW2. The hard limit of 10 items is the same, but while in UW1 a final entry was all zeroes, in UW2 empty entries are all 0xFFFF.

I don't know if these are interesting or appropriate to add to "Guide to the Ultima Underworlds.md", or if you've found any more details about this feature in your deep dives.

Really liking this project and I wish you much success with it!

**Comment by hankmorgan** [comment]
Thanks for this. I've added your notes to the document  (and given you credit). I checked my disassembly and new objects are created with a default quality of 40 as you point out.

Fixed with commit 5d8adad1bf83ae5d29b7dfb5e81da47670f4be54
